substitutions:
  # Unique name for the device in Home Assistant and network
  name: "nix-plus"
  # Friendly name displayed in UIs
  friendly_name: "NIX labs NIX+ Module"
  # Fallback Time Zone in case auto-detection fails
  # Should be POSIX Timezone String
  # Find yours here: https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv
  time_zone: "AEST-10"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: "NIXlabs.NIXPlus"
    version: "0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  core: github://nix-labs/nix_plus/packages/nix_plus_core.yaml@main
  time: github://nix-labs/nix_plus/packages/nix_plus_time.yaml@main
  clock: github://nix-labs/nix_plus/packages/nix_plus_clock.yaml@main
  inputs: github://nix-labs/nix_plus/packages/nix_plus_inputs.yaml@main

external_components:
  # Custom components driving NIX+ and Improv Serial Wi-Fi provisioning
  - source: github://nix-labs/nix_plus@main
    components: [nix_plus, improv_serial]

