substitutions:
  name: "nix-plus"
  friendly_name: "NIX labs NIX+"
  version: "0.9.4"
  time_zone: "AEST-10"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "NIXlabs.NIXPlus"
    version: "${version}"

packages:
  # Using local paths for the GitHub Action Build
  core: !include packages/nix_plus_core.yaml
  update: !include packages/nix_plus_update.yaml
  time: !include packages/nix_plus_time.yaml
  clock: !include packages/nix_plus_clock.yaml
  inputs: !include packages/nix_plus_inputs.yaml

dashboard_import:
  package_import_url: github://nix-labs/nix_plus/nix_plus.yaml@main
  import_full_config: true

# Factory Overrides for Web Interface
web_server:
  id: web_ui
  # Local embedding for factory units (Full offline support)
  js_include: static/www.js
  # Blank out the hosted URL
  js_url: ""

external_components:
  # Using local paths for the GitHub Action Build
  - source:
      type: local
      path: components
    components: [nix_plus, improv_serial]

# Bluetooth Provisioning
esp32_improv:
  authorizer: none

# Serial Provisioning
improv_serial:
  uart_id: uart_bus

