# NIX+ Update Package
# Provides NIX labs managed OTA updates for modules running factory firmware

esphome:
  on_boot:
    - priority: 100
      then:
        - wait_until:
            condition:
              wifi.connected:
        - update.check: firmware_update

ota:
  - platform: http_request # Allow pulling updates from the internet

# Update Check for NIX labs compiled firmware
update:
  - platform: http_request
    id: firmware_update
    name: Firmware Update
    source: https://assets.nixlabs.com.au/nix_plus/firmware/manifest.json
    web_server:
      sorting_group_id: sorting_system
      sorting_weight: 1

button:
  # Consolidated Update Management
  - platform: template
    name: "Update Firmware"
    id: update_firmware_button
    web_server:
      sorting_group_id: sorting_system
      sorting_weight: 4
    on_press:
      then:
        - logger.log: "Initiating firmware update process..."
        - update.check: firmware_update
        - delay: 3s # Allow time for manifest fetch and parsing
        - if:
            condition:
              update.is_available: firmware_update
            then:
              - logger.log: "New version found! Starting Over-The-Air (OTA) update..."
              - update.perform: firmware_update
            else:
              - logger.log: "No update available. Your module is currently up to date."

